# Generated by Django 6.0.2 on 2026-02-11 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.SlugField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.SlugField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('descripcion', models.TextField()),
                ('precio', models.PositiveIntegerField()),
                ('largo_m', models.FloatField()),
                ('alto_m', models.FloatField()),
                ('profundidad_m', models.FloatField()),
                ('peso_kg', models.FloatField()),
                ('stock', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='productos.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Combo',
            fields=[
                ('id', models.SlugField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('ahorro_porcentaje', models.PositiveIntegerField()),
                ('precio_total', models.PositiveIntegerField()),
                ('descripcion_promo', models.TextField()),
                ('productos', models.ManyToManyField(to='productos.producto')),
            ],
        ),
        migrations.CreateModel(
            name='ProductoImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen_url', models.URLField()),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='productos.producto')),
            ],
        ),
    ]
