# Generated by Django 6.0.2 on 2026-02-17 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='alto_m',
            new_name='alto',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='largo_m',
            new_name='largo',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='profundidad_m',
            new_name='profundidad',
        ),
    ]
