# Generated by Django 6.0.2 on 2026-02-20 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_rename_alto_m_producto_alto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combo',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
